name: just_letitgo
description: A simple timer app to keep track of things we've done in the past, to create mild memories.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1

# Run the following command to generate the icons
# dart run flutter_launcher_icons
# dart run launcher_name:main
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  windows:
    generate: true

launcher_name:
  default: "LetitGo"

flutter:
  uses-material-design: true

  assets:
    - assets/